name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: setup
      shell: bash
      run: |
        echo "::group::Setup"
        sudo apt-get update
        sudo apt-get install -y qemu-kvm
        echo "::endgroup::"
    - name: env info
      shell: bash
      run: |
        id
        ls -l /dev/kvm
