name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pwd
      - name: run it
        run: |
          python3 main.py | tee new-output.txt
      - uses: actions/cache/restore@v3
        with:
          key: baseline.txt
          path: baseline.txt
      - continue-on-error: true
        name: compare output
        run: |
          [[ ! -e baseline.txt ]] && echo "[Error] No baseline"
          diff --color=always -pruN output.txt new-output.txt
      - if: ${{ github.event_name == 'push' }}
        uses: actions/cache/restore@v3
        with:
          key: baseline.txt
          path: output.txt

