name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: setup
      shell: bash
      run: |
        echo "::group::Setup"
        sudo apt-get update
        sudo apt-get install -y qemu-kvm
        echo "::endgroup::"
    - uses: actions/checkout@v3
    - name: env info
      shell: bash
      run: |
        id
        ls -l /dev/kvm
        pwd
        ls -lh
    - name: run kvm
      shell: bash
      run: |
        qemu-system-x86_64 \
          -machine accel=kvm,type=q35 \
          -kernel ./bzImage \
          -nographic -m 128m \
          -no-reboot \
          -append 'console=ttyS0 panic=-1'
