name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pwd
      - run: python3 main.py > output.txt
      - uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: output.txt
          path: old-output.txt
      - run: |
          diff --color=always -pruN old-output.txt output.txt || exit 0
      - if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: output.txt
          if-no-files-found: warn
