name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pwd
      - run: python3 main.py > output.txt
      - uses: actions/cache@v3
        with:
          key: output.txt
          path: old-output.txt
      # - uses: actions/download-artifact@v3
      #   continue-on-error: true
      #   with:
      #     name: output.txt
      #     path: old-output.txt
      - continue-on-error: true
        name: compare output
        run: |
          if [[ ! -e old-output.txt ]]; then
            echo [Error] old-output.txt does not exist
            exit 1
          else
            diff --color=always -pruN old-output.txt output.txt
          fi
      - if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: output.txt
          if-no-files-found: warn
