name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pwd
      - name: run it
        run: |
          python3 main.py | tee output.txt
      - uses: actions/cache/restore@v3
        with:
          key: baseline.txt
          restore-keys: |
            baseline.txt-
          path: ~/baseline.txt
      - continue-on-error: true
        name: compare output
        run: |
          diff --color=always -pruN ~/baseline.txt output.txt
      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: cp output.txt ~/baseline.txt
      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: actions/cache/save@v3
        with:
          key: baseline.txt-${{ github.run_id }}
          path: ~/baseline.txt

